version: '3.8'

networks:
  web_test:
    driver: bridge

services:
  proxy:
    image: proxy
    build:
      context: proxy_nginx
    expose:
      - 8080
    ports:
      - "8080:8080"
    networks:
      - web_test

  echo:
    image: echo
    build:
      context: web_golang
    expose:
      - 8080
    networks:
      - web_test

  web:
    image: webtest-web
    env_file:
      - ./server.env
    build:
      #context: ./web_bottle
      #context: ./web_fastAPI
      #context: ./web_falcon
      #context: ./web_tornado
      #context: ./web_flask
      #context: ./web_cherrypy
      #context: ./web_django
      #context: ./web_express
      context: ./web_rubyrails
    expose:
      - 8080
    networks:
      - web_test

  locust_master:
    image: locustio/locust
    command: -f /mnt/locust/locustfile.py --master
    restart: always
    volumes:
      - ./:/mnt/locust
    ports:
      - "8089:8089"
    extra_hosts:
      - host.docker.internal:host-gateway
    networks:
      - web_test
    
  locust_worker:
    image: locustio/locust
    command: -f /mnt/locust/locustfile.py --worker --master-host locust_master
    restart: always
    volumes:
      - ./:/mnt/locust
    extra_hosts:
      - host.docker.internal:host-gateway
    networks:
      - web_test
    depends_on:
      - locust_master
