version: '3.8'

networks:
  web_test:
    driver: bridge
  monitoring_monitoring:
    external: true

volumes:
  sockets:

services:
  proxy:
    image: webtest-proxy
    restart: unless-stopped
    build:
      context: proxy_nginx
    volumes:
      - sockets:/sockets
    expose:
      - 8080
    ports:
      - "8080:8080"
    networks:
      - web_test
    depends_on:
      - web

  web:
    image: registry.127.0.0.1.nip.io:5000/webtest-web
    restart: unless-stopped
    env_file:
      - ./server.env
    build:
      #context: ./web_bottle
      #context: ./web_fastAPI
      #context: ./web_falcon
      #context: ./web_tornado
      #context: ./web_flask
      #context: ./web_cherrypy
      #context: ./web_django
      #context: ./web_express
      #context: ./web_golang
      #context: ./web_nginx
      context: ./web_rubyrails
      #dockerfile: Dockerfile.unicorn
      dockerfile: Dockerfile.puma
    volumes:
      - sockets:/sockets
    expose:
      - 8080
    networks:
      - web_test
      - monitoring_monitoring
    depends_on:
      - echo

  echo:
    image: registry.127.0.0.1.nip.io:5000/webtest-echo
    restart: unless-stopped
    build:
      context: web_golang
    expose:
      - 8080
    networks:
      - web_test
  
  locust:
    image: registry.127.0.0.1.nip.io:5000/locust
    command: -f /mnt/locust/locustfile.py --worker --master-host host.docker.internal
    restart: unless-stopped
    volumes:
      - ./:/mnt/locust
    extra_hosts:
      - host.docker.internal:host-gateway
    networks:
      - web_test
    depends_on:
      - web
      - proxy

#locust_master:
  #  image: locustio/locust
  #  command: -f /mnt/locust/locustfile.py --master
  #  restart: always
  #  volumes:
  ##    - ./:/mnt/locust
  #  extra_hosts:
  #    - host.docker.internal:host-gateway
  #  ports:
  #    - "8089:8089"
    