version: '3.8'

volumes:
  sockets: {}

services:
  proxy:
    image: nginx:latest
    restart: unless-stopped
    volumes:
      - sockets:/sockets
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8000:8000"
    depends_on:
      - web

  web:
    #image: "${REGISTRY:-psaghelyi}/web_express"
    build:
      #context: web_rubyrails
      #dockerfile: Dockerfile.unicorn
      context: web_express
    restart: unless-stopped
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://aws-ot-collector:4317
      - OTEL_RESOURCE_ATTRIBUTES=service.namespace=NSWebTest,service.name=Web,aws.log.group.names=/ecs/web-test
      - OTEL_METRICS_EXPORTER=otlp
      - WORKERS=2
    volumes:
      - sockets:/sockets
    expose:
      - 8080
    depends_on:
      - echo
      - aws-ot-collector

  echo:
    #image: "${REGISTRY:-psaghelyi}/web_express"
    build:
      context: web_express
    restart: unless-stopped
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://aws-ot-collector:4317
      - OTEL_RESOURCE_ATTRIBUTES=service.namespace=NSWebTest,service.name=Echo,aws.log.group.names=/ecs/web-test
      - OTEL_METRICS_EXPORTER=otlp
      - WORKERS=2
    expose:
      - 8080
    depends_on:
      - aws-ot-collector

  aws-ot-collector:
    image: public.ecr.aws/aws-observability/aws-otel-collector:latest
    command: ["--config=/etc/otel-agent-config.yaml"]
    environment:
      - AWS_REGION=${AWS_REGION}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}
      - AWS_EMF_LOG_GROUP_NAME=/ecs/web-test
    volumes:
      - ./otel-config.yaml:/etc/otel-agent-config.yaml
    ports:
      - "13133:13133" # health_check
  
  locust:
    image: "${REGISTRY:-psaghelyi}/locust"
    command: -f /locust/locustfile.py --worker --master-host locust-master
    restart: unless-stopped
    environment:
      - RELAY_URL=http://echo:8080/waitrnd?ms=200
    extra_hosts:
      - host.docker.internal:host-gateway
    depends_on:
      - locust-master

  locust-master:
    image: "${REGISTRY:-psaghelyi}/locust"
    command: -f /locust/locustfile.py --master --host http://host.docker.internal:8000
    restart: unless-stopped
    environment:
      - INFLUXDB_PATH=http://host.docker.internal:8086
    extra_hosts:
      - host.docker.internal:host-gateway
    ports:
      - "8089:8089"
