version: '3.8'

networks:
  web_test:
    driver: bridge

volumes:
  sockets:

services:
  proxy:
    image: webtest-proxy
    build:
      context: proxy_nginx
    volumes:
      - sockets:/sockets
    expose:
      - 8080
    ports:
      - "8080:8080"
    networks:
      - web_test

  web:
    image: webtest-web
    env_file:
      - ./server.env
    build:
      #context: ./web_bottle
      #context: ./web_fastAPI
      #context: ./web_falcon
      #context: ./web_tornado
      #context: ./web_flask
      #context: ./web_cherrypy
      #context: ./web_django
      #context: ./web_express
      #context: ./web_nginx
      context: ./web_rubyrails
    volumes:
      - sockets:/sockets
    expose:
      - 8080
    networks:
      - web_test

  echo:
    image: webtest-echo
    build:
      context: web_golang
    expose:
      - 8080
    networks:
      - web_test
  
  locust:
    image: locustio/locust
    command: -f /mnt/locust/locustfile.py --worker --master-host host.docker.internal
    restart: always
    volumes:
      - ./:/mnt/locust
    extra_hosts:
      - host.docker.internal:host-gateway
    networks:
      - web_test

#locust_master:
  #  image: locustio/locust
  #  command: -f /mnt/locust/locustfile.py --master
  #  restart: always
  #  volumes:
  ##    - ./:/mnt/locust
  #  extra_hosts:
  #    - host.docker.internal:host-gateway
  #  ports:
  #    - "8089:8089"
    