version: '3.7'

services:
  proxy:
    image: proxy
    build:
      context: proxy_nginx
    expose:
      - 8080
    ports:
      - "8080:8080"

  echo:
    image: echo
    build:
      context: web_golang
    expose:
      - 8080

  web:
    image: webtest-web
    env_file:
      - ./server.env
    build:
      #context: ./web_bottle
      #context: ./web_fastAPI
      #context: ./web_falcon
      #context: ./web_tornado
      #context: ./web_flask
      #context: ./web_cherrypy
      #context: ./web_django
      #context: ./web_express
      context: ./web_rubyrails
    expose:
      - 8080
  
  locust_master:
    image: locustio/locust
    ports:
      - "8089:8089"
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - ./:/mnt/locust
    command: -f /mnt/locust/locustfile.py --master
  
  locust_worker:
    image: locustio/locust
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - ./:/mnt/locust
    command: -f /mnt/locust/locustfile.py --worker --master-host locust_master
